### PR TITLE
Update instructions for using the VNC to watch an agent

### PR DESCRIPTION
**Pull request by kevinhughes27**
I got the VNC working! The command in the readme didn't actually work for me but I found a new way by accident. I think using and exposing people to `docker ps` is a good idea though and it lets you easily see all the agents you've got.

### CODE REVIEW

**Comment by bzier** [comment]
At initial glance, this looks good, but I'll take a closer look this evening. It's been a few weeks since I wrote the README, and I'm sure it's not perfect or complete, so I'll review it and your changes more closely later. I'm also curious why the original command didn't work for you. `docker ps` is usually how I find the container info anyway, so I'm also wondering why I chose to mention `docker inspect` instead. Thanks for the PR.

**Comment by kevinhughes27** [comment]
This is the error I got:

```
Template parsing error: template: :1:24: executing "" at <.NetworkSettings.Net...>: can't evaluate field NetworkSettings in type *formatter.containerContext
```

I ran into this before I figured out how --format and Go templates work so it was probably an easy fix that I just didn't understand at the time.

**Comment by kevinhughes27** [comment]
Just noticed this is still open. I think it is still valid, what do you think?

**Comment by bzier** [comment]
Yep, looks valid to me. Not sure why I never merged this... thanks for the reminder

**Pull request merged**
